### ISSUE TITLE
Any example for Convex polytope?

### ISSUE THREAD

**Issue by tl3shi** [danfis/libccd#12]
Is there any example for collision detection between two convex polytopes?

**Comment by danfis** [comment]
Box is a convex polytope and there are examples in src/testsuites for that. If you mean a general polytope then there is no example for that -- it would highly depend on the definition of the polytope anyway. If you need to work with polytopes just think about a proper support function (or search literature).

**Comment by tl3shi** [comment]
Thank you for you reply.  If the convex polyhedron is defined as following:
```
Polyhedron:
    vector<Polygon3D>;
Polygon3D:
    uvec3 normal;
    vector<vec3> points;
```
In the support function ```ccdSupport(const void * convex, const ccd_vec3_t *_dir,  ccd_vec3_t *v) ```, I need fill the variable v, which should be an intersection point between one Polygon3D and the ray with normal ```_dir``` , and the intersection point should be the one that has maximum dot value with the normal.  
Am i right?

**Comment by tl3shi** [comment]
Or just select the known points of the Polygon3D, like the following code segment, I copyed from [here](https://github.com/YumeYami/ode_se/blob/8970e802e703065b271e7e5aaf295e34207f25df/ode/src/collision_libccd.cpp) 

I am doubting that the following way is  OK. 

```cpp
static void ccdSupportConvex(const void *obj, const ccd_vec3_t *_dir, ccd_vec3_t *v)
{
    const ccd_convex_t *c = (const ccd_convex_t *)obj;
    ccd_vec3_t dir, p;
    ccd_real_t maxdot, dot;
    size_t i;
    dReal *curp;

    ccdVec3Copy(&dir, _dir);
    ccdQuatRotVec(&dir, &c->o.rot_inv);

    maxdot = -CCD_REAL_MAX;
    curp = c->convex->points;
    for (i = 0; i < c->convex->pointcount; i++, curp += 3){
        ccdVec3Set(&p, curp[0], curp[1], curp[2]);
        dot = ccdVec3Dot(&dir, &p);
        if (dot > maxdot){
            ccdVec3Copy(v, &p);
            maxdot = dot;
        }
    }
    // transform support vertex
    ccdQuatRotVec(v, &c->o.rot);
    ccdVec3Add(v, &c->o.pos);
}
```

**Comment by danfis** [comment]
The ccdSupportConvex() function seems ok -- the support point is the vertex from the polyhedron that is furthest along the direction vector (dot product says you the length of projection on the direction vector)... But if you are unsure, try some literature.

**Comment by danfis** [comment]
Now when I think about it, I think the code you posted was originaly written by me (as part of ODE physic SDK). So I would say it is correct. :)

**Comment by tl3shi** [comment]
Thanks. It is correct. 
Some papers said that the procedure can be optimazed to constant time when in moving environment.
