### ISSUE TITLE
ccdGJKPenetration() returns 0 when contact and -1 when not contact?

### ISSUE THREAD

**Issue by ChenguangZhang** [danfis/libccd#16]
The markdown page says return values are true/false when contact/not-contact, but several tests show the return values are 0/-1 respectively, so 0 corresponds to true and -1 correspond to false?
This is contradictory to the common C/C++ practice.

**Comment by danfis** [comment]
*Intersect() functions returns true/false, but *Penetration() functions return 0 for success and -1 otherwise. I will check the manual and fix it.
