### ISSUE TITLE
Instructions for make not working

### ISSUE THREAD

**Issue by sdenenberg** [danfis/libccd#20]
Hello,

Per the instructions, I cloned the directory, navigated to source, ran make.  The error I am getting is the following:

m4  -DUSE_DOUBLE ccd/config.h.m4 >ccd/config.h
/bin/sh: 1: m4: not found
make: *** [ccd/config.h] Error 127

Looking at the ccd folder, there is no config.h, so it is not surprising that it can't be found.

Am I missing something?  I am running Ubuntu 14.04.

Thanks,

Scott

**Comment by danfis** [comment]
Hi,
you need to install m4 macro processor.
   Dan
