### ISSUE TITLE
Can't build latest commit on Ubuntu 12.04

### ISSUE THREAD

**Issue by EdsterG** [danfis/libccd#28]
Get the following error:

[ 22%] Built target ccd
[ 29%] Built target cu
[ 33%] Linking C executable bench2
cu/libcu.a(cu.c.o): In function `cuTimerStop':
cu.c:(.text+0x73f): undefined reference to `clock_gettime'
cu/libcu.a(cu.c.o): In function `cuTimerStart':
cu.c:(.text+0x72b): undefined reference to `clock_gettime'
collect2: ld returned 1 exit status

**Comment by EdsterG** [comment]
@jamiesnape The cmake refactor causes this error. I can compile from any commit before the cmake refactor.

**Comment by jamiesnape** [comment]
Before that commit the test suite was not built. As a work around, you can disable the test suite with with `cmake  -DBUILD_TESTING`. Which version of CMake are you using and does compilation with Autotools work?
