### ISSUE TITLE
Edge/Vertex order in ccd_pt_face_t

### ISSUE THREAD

**Issue by hongkai-dai** [danfis/libccd#45]
Is there any ordering on the three edges, stored in [ccd_pt_face_t](https://github.com/danfis/libccd/blob/master/src/polytope.h#L84)? I want to compute the normal of a face, pointing away from the polytope. I compute the normal as `n = e₁.cross(e₂)`, but this normal `n` does not necessarily points away from the polytope. 

If the edges are always stored in a specific order (counter clockwise order, for example), then we can always guarantee the cross product `e₁.cross(e₂)` points away from the polytope. Does libccd guarantee such ordering? Is there a good way to always get the normal vector pointing away from the polytope?

**Comment by danfis** [comment]
There is no guarantee, you have to find where is inside and where outside of the polytope by other means.
